RESOURCES_FOLDER = 'res/'
IMAGES_FOLDER = f'{RESOURCES_FOLDER}img/'
FONTS_FOLDER = f'{RESOURCES_FOLDER}fonts/'
TEMP_FOLDER = '/tmp/'

BASE_PATH = f'{IMAGES_FOLDER}base.png'
FONT_PATH = F'{FONTS_FOLDER}MonospaceBold.ttf'